ocsinventory-job

diff --git a/kubernetes/apps/base/self-hosted/ocsinventory/job-helmrelease.yaml b/kubernetes/apps/base/self-hosted/ocsinventory/job-helmrelease.yaml
--- a/kubernetes/apps/base/self-hosted/ocsinventory/job-helmrelease.yaml
+++ b/kubernetes/apps/base/self-hosted/ocsinventory/job-helmrelease.yaml
@@ -48,12 +48,21 @@ spec:
               - /bin/sh
               - -c
               - |
-                echo "Waiting 10 seconds before executing..."
+                echo "[INFO] Waiting 10 seconds before starting..."
                 sleep 10
                 POD=$(kubectl get pod -l app.kubernetes.io/name=ocsinventory -n self-hosted -o jsonpath="{.items[0].metadata.name}")
+                if [ -z "$POD" ]; then
+                  echo "[ERROR] No ocsinventory pod found. Exiting."
+                  exit 1
+                fi
+                echo "[INFO] Found Pod: $POD"
                 kubectl exec -n self-hosted $POD -c app -- \
                   sh -c 'cd /usr/share/ocsinventory-reports/ocsreports/crontab && php cron_all_software.php'
-                echo "Waiting 10 seconds after executing..."
+                if [ $? -ne 0 ]; then
+                  echo "[ERROR] Command execution failed inside the pod."
+                  exit 2
+                fi
+                echo "[SUCCESS] Script executed successfully in $POD."
                 sleep 10
             resources:
               requests:
